version: 2
updates:
  # TFLint (Terraform linter)
  - package-ecosystem: "terraform"
    directory: "/"                 # Root directory of the repository
    schedule:
      interval: "weekly"           # Run updates weekly (adjust as needed)
    allow:
      - dependency-name: "tflint"  # Only target TFLint updates
    labels:
      - "tflint"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"                 # Root directory of the repository
    schedule:
      interval: "weekly"           # Run updates weekly
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"